#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Remove directories that start with a digit from 1 to 9 and end with a 0
rm -rf [1-9]*0/

# Remove directories that start with a digit from 1 to 9 and end with a 0
rm -f log*

#------------------------------------------------------------------------------
